[package]
name = "penumbra-nft"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
blake3 = "1.3"
penumbra-crypto = "*"
uuid = { version = "1.4", features = ["v4"] }
